### ISSUE TITLE
Exporter no longer works with OpenVPN AS 2.14.0

### ISSUE THREAD

**Issue by rtuk** [rossigee/openvpnas-exporter#57]
In OpenVPN AS 2.14.0 the output of sacli subscriptionstatus has been updated, the exporter now fails with:
Failed to call GetSubscriptionStatus: reading body cannot find field 'Subkey' on struct

See release notes:
https://openvpn.net/as-docs/as-2-14-release-notes.html#access-server-2-14-versions

Fields that have been added seem to be:
- billing_id
- subkey

**Comment by rossigee** [comment]
I'm not actually using OpenVPN-AS myself any more. I'd be happy to merge a reasonable-looking PR, but I can't write or test it.

**Comment by rtuk** [comment]
Added [#58](https://github.com/rossigee/openvpnas-exporter/pull/58)
These changes have been tested on OpenVPN-AS 2.14.0
